baseURL = "/"
languageCode = "en-us"
title = "EA Resources"
theme = "ananke"

SectionPagesMenu = "main"

summarylength = 6

[params]
featured_image = "/img/LandingBanner-lower3.png"
logo = "/img/logo_transparent.png"
custom_css = ["css/custom.css"]
