baseURL = "/"
languageCode = "en-us"
title = "EA Hub"
theme = "ananke"

SectionPagesMenu = "main"

summarylength = 6

[params]
featured_image = "/img/ParallaxFaces19.png"
custom_css = ["css/custom.css"]
