backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/img" # Folder where user uploaded files should go
public_folder: "img"
publish_mode: editorial_workflow #prevents changes from going live immediately after being saved.


collections: # A list of collections the CMS should be able to edit
  - name: "evaluation_and_strategy" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Evaluation and Strategy" # Used in the UI, ie.: "New Post"
    folder: "content/evaluation_and_strategy" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Illustration", name: "illustration", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tag", name: "tag", widget: "string", required: false}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Original Publication URL", name: "originalPublicationURL", widget: "string", required: false}
      - {label: "Blocked", name: "block", widget: "boolean", required: false}
      - label: "License"
        name: "license"
        widget: "list"
        required: false
        fields:
        - {label: "Name", name: "name", widget: "string", default: "Creative Commons Attribution-ShareAlike 3.0"}
        - {label: "URL", name: "url", widget: "string", default: "https://creativecommons.org/licenses/by-sa/3.0/legalcode"}
      - label: "Related Articles"
        name: "relatedArticles"
        widget: "list"
        required: false
        fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "URL", name: "url", widget: "string"}

  - name: "events_and_activities" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Events and Activities" # Used in the UI, ie.: "New Post"
    folder: "content/events_and_activities" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Illustration", name: "illustration", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tag", name: "tag", widget: "string", required: false}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Original Publication URL", name: "originalPublicationURL", widget: "string", required: false}
      - {label: "Blocked", name: "block", widget: "boolean", required: false}
      - label: "License"
        name: "license"
        widget: "list"
        required: false
        fields:
        - {label: "Name", name: "name", widget: "string", default: "Creative Commons Attribution-ShareAlike 3.0"}
        - {label: "URL", name: "url", widget: "string", default: "https://creativecommons.org/licenses/by-sa/3.0/legalcode"}
      - label: "Related Articles"
        name: "relatedArticles"
        widget: "list"
        required: false
        fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "URL", name: "url", widget: "string"}

  - name: "guides_and_tips" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Guides and Tips" # Used in the UI, ie.: "New Post"
    folder: "content/guides_and_tips" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Illustration", name: "illustration", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tag", name: "tag", widget: "string", required: false}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Original Publication URL", name: "originalPublicationURL", widget: "string", required: false}
      - {label: "Blocked", name: "block", widget: "boolean", required: false}
      - label: "License"
        name: "license"
        widget: "list"
        required: false
        fields:
        - {label: "Name", name: "name", widget: "string", default: "Creative Commons Attribution-ShareAlike 3.0"}
        - {label: "URL", name: "url", widget: "string", default: "https://creativecommons.org/licenses/by-sa/3.0/legalcode"}
      - label: "Related Articles"
        name: "relatedArticles"
        widget: "list"
        required: false
        fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "URL", name: "url", widget: "string"}

  - name: "start_group" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Start an EA Group" # Used in the UI, ie.: "New Post"
    folder: "content/start_a_group" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Illustration", name: "illustration", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tag", name: "tag", widget: "string", required: false}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Original Publication URL", name: "originalPublicationURL", widget: "string", required: false}
      - {label: "Blocked", name: "block", widget: "boolean", required: false}
      - label: "License"
        name: "license"
        widget: "list"
        required: false
        fields:
        - {label: "Name", name: "name", widget: "string", default: "Creative Commons Attribution-ShareAlike 3.0"}
        - {label: "URL", name: "url", widget: "string", default: "https://creativecommons.org/licenses/by-sa/3.0/legalcode"}
      - label: "Related Articles"
        name: "relatedArticles"
        widget: "list"
        required: false
        fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "URL", name: "url", widget: "string"}

  - name: "materials_and_templates" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Materials and Templates" # Used in the UI, ie.: "New Post"
    folder: "content/materials_and_templates" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Illustration", name: "illustration", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tag", name: "tag", widget: "string", required: false}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Original Publication URL", name: "originalPublicationURL", widget: "string", required: false}
      - {label: "Blocked", name: "block", widget: "boolean", required: false}
      - label: "License"
        name: "license"
        widget: "list"
        required: false
        fields:
        - {label: "Name", name: "name", widget: "string", default: "Creative Commons Attribution-ShareAlike 3.0"}
        - {label: "URL", name: "url", widget: "string", default: "https://creativecommons.org/licenses/by-sa/3.0/legalcode"}
      - label: "Related Articles"
        name: "relatedArticles"
        widget: "list"
        required: false
        fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "URL", name: "url", widget: "string"}


  - name: "pages"
    label: "Pages"
    files:
      - file: "content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Featured_Immage, name: featured_image, widget: image}
          - label: "Action Links"
            name: "actionLinks"
            widget: "list"
            fields:
            - {label: "Name", name: "name", widget: "string"}
            - {label: "URL", name: "url", widget: "string"}
            - {label: "contact", name: "contact", widget: "boolean", required: false}
          - label: "Calendar"
            name: "calendar"
            widget: "object"
            fields:
            - {label: "Title", name: "title", widget: "string"}
            - {label: "URL", name: "url", widget: "string"}
            - {label: "Image Link", name: "imageLink", widget: "image"}
      - file: "content/about/_index.md" # Used in routes, ie.: /admin/collections/:slug/edit
        label: "About" # Used in the UI, ie.: "New Post"
        name: "about"
        fields:
        - {label: Title, name: title, widget: string}
        - {label: Image, name: image, widget: image}
        - {label: Body, name: body, widget: markdown}
        - label: "Tech Support Contact"
          name: "techSupportContact"
          widget: "object"
          fields:
          - {label: "LinkText", name: "linkText", widget: "string"}
          - {label: "Link", name: "link", widget: "string"}
        - label: "Suggestions Contact"
          name: "suggestionsContact"
          widget: "object"
          fields:
          - {label: "LinkText", name: "linkText", widget: "string"}
          - {label: "Link", name: "link", widget: "string"}
