backend:
  name: git-gateway
  branch: development # Branch to update (optional; defaults to master)

media_folder: "static/img" # Folder where user uploaded files should go
public_folder: "img"
publish_mode: editorial_workflow #prevents changes from going live immediately after being saved.


collections: # A list of collections the CMS should be able to edit
  #EVENTS
  - name: "events" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Events" # Used in the UI, ie.: "New Post"
    folder: "content/events" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Illustration", name: "illustration", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tag", name: "tag", widget: "string", required: false}
      - {label: "Original Publication URL", name: "originalPublicationURL", widget: "string", required: false}
      - {label: "Weight", name: "weight", widget: "number", required: false}
      - {label: "Pictogram", name: "pictogram", widget: "image", required: false}
      - label: "License"
        name: "license"
        widget: "list"
        required: false
        fields:
        - {label: "Name", name: "name", widget: "string", default: "Creative Commons Attribution-ShareAlike 3.0"}
        - {label: "URL", name: "url", widget: "string", default: "https://creativecommons.org/licenses/by-sa/3.0/legalcode"}

  - name: "events_articles" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Events - Articles" # Used in the UI, ie.: "New Post"
    folder: "content/events/articles" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"; required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Illustration", name: "illustration", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tag", name: "tag", widget: "string", required: false}
      - {label: "Original Publication URL", name: "originalPublicationURL", widget: "string", required: false}
      - label: "License"
        name: "license"
        widget: "list"
        required: false
        fields:
        - {label: "Name", name: "name", widget: "string", default: "Creative Commons Attribution-ShareAlike 3.0"}
        - {label: "URL", name: "url", widget: "string", default: "https://creativecommons.org/licenses/by-sa/3.0/legalcode"}

  # START AN EA GROUP
  - name: "start" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Start an EA Group" # Used in the UI, ie.: "New Post"
    folder: "content/start" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Illustration", name: "illustration", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tag", name: "tag", widget: "string", required: false}
      - {label: "Original Publication URL", name: "originalPublicationURL", widget: "string", required: false}
      - {label: "Weight", name: "weight", widget: "number", required: false}
      - {label: "Pictogram", name: "pictogram", widget: "image", required: false}
      - label: "License"
        name: "license"
        widget: "list"
        required: false
        fields:
        - {label: "Name", name: "name", widget: "string", default: "Creative Commons Attribution-ShareAlike 3.0"}
        - {label: "URL", name: "url", widget: "string", default: "https://creativecommons.org/licenses/by-sa/3.0/legalcode"}

  - name: "start_articles" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Start an EA Group - Articles" # Used in the UI, ie.: "New Post"
    folder: "content/start/articles" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"; required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Illustration", name: "illustration", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tag", name: "tag", widget: "string", required: false}
      - {label: "Original Publication URL", name: "originalPublicationURL", widget: "string", required: false}
      - label: "License"
        name: "license"
        widget: "list"
        required: false
        fields:
        - {label: "Name", name: "name", widget: "string", default: "Creative Commons Attribution-ShareAlike 3.0"}
        - {label: "URL", name: "url", widget: "string", default: "https://creativecommons.org/licenses/by-sa/3.0/legalcode"}

  # TIPS ON RUNNING A GROUP
  - name: "tips" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Tips on Running a Group" # Used in the UI, ie.: "New Post"
    folder: "content/tips" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Illustration", name: "illustration", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tag", name: "tag", widget: "string", required: false}
      - {label: "Original Publication URL", name: "originalPublicationURL", widget: "string", required: false}
      - {label: "Weight", name: "weight", widget: "number", required: false}
      - {label: "Pictogram", name: "pictogram", widget: "image", required: false}
      - label: "License"
        name: "license"
        widget: "list"
        required: false
        fields:
        - {label: "Name", name: "name", widget: "string", default: "Creative Commons Attribution-ShareAlike 3.0"}
        - {label: "URL", name: "url", widget: "string", default: "https://creativecommons.org/licenses/by-sa/3.0/legalcode"}

  - name: "tips_articles" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Tips on Running a Group - Articles" # Used in the UI, ie.: "New Post"
    folder: "content/tips/articles" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"; required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Illustration", name: "illustration", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tag", name: "tag", widget: "string", required: false}
      - {label: "Original Publication URL", name: "originalPublicationURL", widget: "string", required: false}
      - label: "License"
        name: "license"
        widget: "list"
        required: false
        fields:
        - {label: "Name", name: "name", widget: "string", default: "Creative Commons Attribution-ShareAlike 3.0"}
        - {label: "URL", name: "url", widget: "string", default: "https://creativecommons.org/licenses/by-sa/3.0/legalcode"}

  #LEARN
  - name: "learn" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Learn" # Used in the UI, ie.: "New Post"
    folder: "content/learn" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Illustration", name: "illustration", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tag", name: "tag", widget: "string", required: false}
      - {label: "Original Publication URL", name: "originalPublicationURL", widget: "string", required: false}
      - {label: "Weight", name: "weight", widget: "number", required: false}
      - {label: "Pictogram", name: "pictogram", widget: "image", required: false}
      - label: "License"
        name: "license"
        widget: "list"
        required: false
        fields:
        - {label: "Name", name: "name", widget: "string", default: "Creative Commons Attribution-ShareAlike 3.0"}
        - {label: "URL", name: "url", widget: "string", default: "https://creativecommons.org/licenses/by-sa/3.0/legalcode"}

  - name: "learn_articles" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Learn - Articles" # Used in the UI, ie.: "New Post"
    folder: "content/learn/articles" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"; required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Illustration", name: "illustration", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tag", name: "tag", widget: "string", required: false}
      - {label: "Original Publication URL", name: "originalPublicationURL", widget: "string", required: false}
      - label: "License"
        name: "license"
        widget: "list"
        required: false
        fields:
        - {label: "Name", name: "name", widget: "string", default: "Creative Commons Attribution-ShareAlike 3.0"}
        - {label: "URL", name: "url", widget: "string", default: "https://creativecommons.org/licenses/by-sa/3.0/legalcode"}

  #TAKE ACTION
  - name: "take_action" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Take Action" # Used in the UI, ie.: "New Post"
    folder: "content/take_action" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Illustration", name: "illustration", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tag", name: "tag", widget: "string", required: false}
      - {label: "Original Publication URL", name: "originalPublicationURL", widget: "string", required: false}
      - {label: "Weight", name: "weight", widget: "number", required: false}
      - {label: "Pictogram", name: "pictogram", widget: "image", required: false}
      - label: "License"
        name: "license"
        widget: "list"
        required: false
        fields:
        - {label: "Name", name: "name", widget: "string", default: "Creative Commons Attribution-ShareAlike 3.0"}
        - {label: "URL", name: "url", widget: "string", default: "https://creativecommons.org/licenses/by-sa/3.0/legalcode"}

  - name: "take_action_articles" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Take Action - Articles" # Used in the UI, ie.: "New Post"
    folder: "content/take_action/articles" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"; required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Illustration", name: "illustration", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tag", name: "tag", widget: "string", required: false}
      - {label: "Original Publication URL", name: "originalPublicationURL", widget: "string", required: false}
      - label: "License"
        name: "license"
        widget: "list"
        required: false
        fields:
        - {label: "Name", name: "name", widget: "string", default: "Creative Commons Attribution-ShareAlike 3.0"}
        - {label: "URL", name: "url", widget: "string", default: "https://creativecommons.org/licenses/by-sa/3.0/legalcode"}

  - name: "pages"
    label: "Pages"
    create: true
    files:
      - file: "content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Featured_Immage, name: featured_image, widget: image}
          - label: "Action Links"
            name: "actionLinks"
            widget: "list"
            fields:
            - {label: "Name", name: "name", widget: "string"}
            - {label: "URL", name: "url", widget: "string"}
            - {label: "contact", name: "contact", widget: "boolean", required: false}
          - label: "Calendar"
            name: "calendar"
            widget: "object"
            fields:
            - {label: "Title", name: "title", widget: "string"}
            - {label: "URL", name: "url", widget: "string"}
            - {label: "Image Link", name: "imageLink", widget: "image"}
      - file: "content/about/_index.md" # Used in routes, ie.: /admin/collections/:slug/edit
        label: "About" # Used in the UI, ie.: "New Post"
        name: "about"
        fields:
        - {label: Title, name: title, widget: string}
        - {label: Image, name: image, widget: image}
        - {label: Body, name: body, widget: markdown}
        - label: "Tech Support Contact"
          name: "techSupportContact"
          widget: "object"
          fields:
          - {label: "LinkText", name: "linkText", widget: "string"}
          - {label: "Link", name: "link", widget: "string"}
        - label: "Suggestions Contact"
          name: "suggestionsContact"
          widget: "object"
          fields:
          - {label: "LinkText", name: "linkText", widget: "string"}
          - {label: "Link", name: "link", widget: "string"}
